version: '3'

services:
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      MEMORY_LIMIT: 20480M
      UPLOAD_LIMIT: 3000M
    restart: always
    ports:
      - "80:80"
  backend:
    container_name: backend
    depends_on:
      - mysql
    ports:
      - "8000:8000"
    build:
      context: .
      dockerfile: Dockerfile
    image: jasonkhau/backend:latest

volumes:
  db_data: