server:
  port: 1222
jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY
  expiration: 84600
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fqc
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update